In [34]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import thing

img = cv2.imread('lanes.png')

In [36]:
lines = thing.detect_lines(img, 49, 50, 3, 500, 40)
print(lines)
plt.imshow(cv2.cvtColor(thing.draw_lines(img, lines), cv2.COLOR_BGR2RGB))


thing.get_slopes_intercepts(lines)

plt.show()

[[[1007 2133 1394 1489]]

 [[1428 2137 1564 1547]]

 [[3047 1176 3727 1308]]

 [[2908 1152 3725 1311]]

 [[1426 2134 1552 1586]]

 [[1065 2024 1434 1410]]

 [[2906 1151 3726 1310]]]


ValueError: too many values to unpack (expected 4)